### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by ihaveacrushonjaidenanimations2068** [Ocelot5836/OpenDeviceMod#1]
---- Minecraft Crash Report ----
// You're mean.

Time: 3/23/20 1:20 AM
Description: Exception in server tick loop

java.lang.AbstractMethodError: Method com/ocelot/opendevices/core/LaptopTileEntity.getPos()Lnet/minecraft/util/math/BlockPos; is abstract
	at com.ocelot.opendevices.core.LaptopTileEntity.getPos(LaptopTileEntity.java) ~[?:0.1.0-pre] {re:classloading}
	at com.ocelot.opendevices.core.registry.TileEntityDeviceSerializer.write(TileEntityDeviceSerializer.java:34) ~[?:0.1.0-pre] {re:classloading}
	at com.ocelot.opendevices.core.registry.TileEntityDeviceSerializer.write(TileEntityDeviceSerializer.java:16) ~[?:0.1.0-pre] {re:classloading}
	at com.ocelot.opendevices.core.devicemanager.DeviceManagerSavedData.add(DeviceManagerSavedData.java:48) ~[?:0.1.0-pre] {re:classloading}
	at com.ocelot.opendevices.api.device.DeviceTileEntity.setAddress(DeviceTileEntity.java:41) ~[?:0.1.0-pre] {re:classloading}
	at com.ocelot.opendevices.api.device.DeviceTileEntity.onLoad(DeviceTileEntity.java:66) ~[?:0.1.0-pre] {re:classloading}
	at net.minecraft.world.World.func_175700_a(World.java:573) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_175690_a(World.java:885) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:289) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_180501_a(World.java:192) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.item.BlockItem.func_195941_b(BlockItem.java:146) ~[?:?] {re:classloading}
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:54) ~[?:?] {re:classloading}
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:607) ~[?:?] {re:classloading}
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:162) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:328) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:847) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil$$Lambda$4136/1659967614.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1151641456 bytes (1098 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.0
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.0-client.jar Minecraft {minecraft@1.14.4 DONE}
		forge-1.14.4-28.2.0-universal.jar Forge {forge@28.2.0 DONE}
		opendevices-0.1.0-pre.jar Open Device Mod {opendevices@0.1.0-pre DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['VaraHunter'/27, l='New World', x=77.50, y=4.00, z=-104.36]]
	Data Packs: vanilla, mod:forge, mod:opendevices
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by ihaveacrushonjaidenanimations2068** [comment]
seems to still happen

**Comment by ihaveacrushonjaidenanimations2068** [comment]
[crash-2020-03-26_15.55.19-server.txt](https://github.com/Ocelot5836/OpenDeviceMod/files/4385837/crash-2020-03-26_15.55.19-server.txt)

**Comment by Ocelot5836** [comment]
What environment is this happening in?

**Comment by ihaveacrushonjaidenanimations2068** [comment]
i compiled it and im running it n the launcher

**Comment by ihaveacrushonjaidenanimations2068** [comment]
a dev env yields no crash
